routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Render home
Route::get('/', 'SupportAboutFaqController@aboutUs');
Route::get('/home', function () {
    return view('/');
});

// render welcome page
Route::get('/welcome', function () {
    return view('welcome');
});
// render about page
// Route::get('/about', function () {
//     return view('about-us');
// });
Route::get('/about', 'SupportAboutFaqController@aboutUs')->name('about');
Route::get('/support', 'SupportAboutFaqController@displayFaq')->name('supports');
// Get Token
Route::post('/get-token', 'DataController@generateToken');
// Destroy Token
Route::post('/destroy-token', 'DataController@destroyToken');
Route::get('/reset-password', 'FirebaseController@resetPassword');
Route::get('/save', 'FirebaseController@savePassword')->name('setpassword');
// Route::get('/verify/email/{token}', 'Apps_UserController@mailVerify');
// Protected routes
Route::group(['middleware' => ['jwt.verify']], function() {
    Route::get('/apps/users/', 'Login_UserController@users');
    Route::post('/profile/update', 'profileUpdateController@userUpdate');
    Route::get('/user/{user_id}', 'profileUpdateController@userInfo');
    Route::post('/user/social/signup/','SocialController@socialSignup');
    Route::post('/user/login', 'Login_UserController@loginUser');
    Route::post('/user/register', 'Apps_UserController@appsUser');
    Route::get('/users/category/{category_id}', 'CategoryController@usersByCategory');
    Route::get('/category/{category_id}', 'CategoryController@category');
    Route::get('/user-profile/{id}', 'UsersProfilesController@userProfile');
   
    Route::post('/questions/ask/', 'questionContents@askQuestion');
    Route::post('/cancel/assignment/', 'assignmentPaymentController@cancelAssignment');
    Route::get('/questions/my/{user_id}', 'questionsController@askedQuestions');
    Route::get('/questions/all', 'questionsController@allQuestions');
    Route::get('/question/details/{id}', 'questionsController@getQuestion');
    Route::get('/questions/assigned/{user_id}', 'questionsController@assignedQuestion');
    Route::post('/questions/filter', 'filterAnswersController@filter');
    Route::post('/prepayments/to', 'transactionsController@prePayments');
    Route::get('/prepayments/my/{user_id}', 'PrepaymentRequestController@MyRequest');
    Route::post('/prepayments/request/update', 'PrepaymentRequestController@updateRequest');
    Route::get('/prepayments/requested/{user_id}', 'PrepaymentRequestController@PreRequested');
    Route::post('/assignment/pay', 'assignmentPaymentController@assignmentPayment');
    Route::post('/assignment/request/update', 'questionsController@assignmentUpdate');

    Route::get('/answer/all', 'ansQuestionsController@allAnswers');
    Route::post('/submit/assignment', 'ansQuestionsController@assignSubmit');
    Route::post('/submit/answer', 'ansQuestionsController@replyAns');
    Route::get('/answer/my/{user_id}', 'ansQuestionsController@myAnswers');                        
    Route::post('/answer/buy/', 'purchaseAnsController@purchaseAns');
    Route::get('/paid/answer/{user_id}', 'purchaseAnsController@MyBuyAnswer');
    Route::post('/delivery/update', 'assignmentPaymentController@deliveryUpdate');
    Route::get('/quizzes/ans', 'quizzesController@ansAtempts');
    Route::get('/user/quiz/{user_id}', 'quizzesController@ansAtempts');
    Route::get('/categories/all', 'CategoryController@categoryAll');
    Route::get('/category/all/{user_id}', 'CategoryController@usercategoryAll');
    Route::post('/category/quizzes', 'CategoryController@categoryQuizzes');
    Route::post('/answer/quiz', 'CategoryController@answerQuiz');
    Route::post('/quizzes/questions', 'quizzesController@quizAttempts');
    Route::post('/quizzes/attempt', 'replyQuizzeeController@quizAns');
    Route::post('/account/funds/add', 'addFundsController@addFunds'); 
    Route::post('/account/withdrawal', 'withdrawalAmountController@withdrawal');
    Route::get('/fetch/transaction/', 'transactionsController@fetch');
    Route::post('/chat/message', 'chatMessageController@chats');
    Route::get('/chat/reply', 'chatMessageController@preference');
    Route::get('/my/transaction/{id}', 'transactionsController@myTransaction');
    Route::get('/get/balance/{user_id}', 'transactionsController@balance');
    Route::post('/feedback/review', 'feedbacksController@feedback');
    Route::get('/search/{search_key}', 'filterAnswersController@search');
    Route::get('/feedback/my/{user_id}', 'feedbacksController@myFeedback');
    Route::post('/create/category', 'CategoryController@categoryCreate');
    Route::get('/app/user-profile/{registration_token}', 'Apps_UserController@getUser');
    Route::post('/ondemand/connect', 'AppUsersController@onDemandConnect');
    Route::post('/ondemand/disconnect', 'AppUsersController@onDemandDisconnect');
});    

Auth::routes();
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/logout', 'HomeController@logout')->name('home');
Route::group(['prefix'=>'dashboard','as'=>'dashboard.','middleware' => 'auth'], function(){
    Route::get('profile-update', 'AppUsersController@editProfile')->name('profile-update');
    Route::get('cancelled/assigment', 'AssignmentQuestionAnswerController@cancelledAssignment')->name('cancelled-assignment'); 
    Route::get('save', 'AppUsersController@savePaypal')->name('savepaypl'); 
    Route::get('assignment/questions', 'AssignmentQuestionAnswerController@assignment')->name('question');
    Route::get('refund-accept/{id}', 'AssigmentTransactionController@refundAccept')->name('refund-approve');
    Route::get('refund-reject/{id}', 'AssigmentTransactionController@refundReject')->name('refund-reject');
    Route::get('create/new/user', 'AppUsersController@createUser')->name('add');
    Route::get('cancelled/assignment', 'AssigmentTransactionController@cancellAssignmentList')->name('cancel-assignment');
    Route::post('refund/request/update', 'WithdrawalController@refundRequestUpdate')->name('refund-request.update');
    Route::post('withdrawal/request', 'WithdrawalController@withdrawalApprove')->name('withdrawal-request.update');
    Route::get('withdrawal/handle/{status}', 'WithdrawalController@withdrawalHandle')->name('withdrawal.handle');
    Route::get('refund/handle/{status}', 'WithdrawalController@refundHandle')->name('refund.handle');
    Route::get('withdrawal/request', 'AssigmentTransactionController@withdrawalRequest')->name('withdrawal');
    Route::get('profile', 'AppUsersController@myProfile')->name('myprofile');
    Route::get('my/transaction', 'AppUsersController@myTrasactionHistory')->name('mytransaction');

    Route::group(['prefix'=>'users','as'=>'user.'], function(){
        Route::get('update', 'AppUsersController@updateProfile')->name('update');
        Route::get('questions/edit/{id}', 'AssignmentQuestionAnswerController@editAllQuetion')->name('edit-post'); 
        Route::get('questions/delete/{id}', 'AssignmentQuestionAnswerController@deletePostQuestion')->name('delete-post'); 
        Route::get('delete/{id}', 'AppUsersController@deleteUser')->name('delete');
       
        Route::get('unblock/{id}', 'AppUsersController@unblock')->name('unblock');
        Route::get('block/{id}', 'AppUsersController@updateBlock')->name('toblock');
        Route::post('create', 'AppUsersController@createNewUser')->name('create-new-user');
        Route::post('create/dashboard', 'AppUsersController@createDasboardUser')->name('dash-new-user');
        Route::post('create/both-user', 'AppUsersController@createBothUser')->name('both-user');
        Route::get('/', 'AppUsersController@usersList')->name('list');
        Route::get('blocked', 'AppUsersController@blockUser')->name('block');
        Route::get('account', 'withdrawalAmountController@myAccount')->name('myaccount');
        Route::get('transaction', 'transactionsController@getTransactions')->name('transaction');
    });

    Route::group(['prefix'=>'category','as'=>'category.'], function(){
        Route::get('create',function(){
            return view('category.create-category');
        })->name('create');
        Route::get('edit/{id}', 'CreateCategoryController@edit')->name('edit');
        Route::get('create-category', 'CreateCategoryController@createCategory')->name('CreateCatogry');
        Route::get('/manage','CreateCategoryController@allCategory')->name('manage');
        Route::get('{id}', 'CreateCategoryController@delete')->name('delcategory');
        Route::get('update/{id}', 'CreateCategoryController@updateCategory')->name('update');        
    });

    Route::group(['prefix'=>'quiz','as'=>'quiz.'], function(){
        Route::get('/del/{id}','QuizCategoryController@delQuiz')->name('del');
        Route::get('/all/{id}','QuizCategoryController@allQuiz')->name('show');
        Route::get('/create','QuizCategoryController@quizzAllCreate')->name('create-quiz');
        Route::get('/manage','QuizCategoryController@allQuizzes')->name('manage-quiz');
        Route::get('create/', 'QuizCategoryController@createQuiz')->name('create');
    });

    Route::get('questions', 'AssignmentQuestionAnswerController@allQuestionAnswer')->name('all-question');
    
    Route::get('create/faq',function () {
        return view('support_faq.create_faq');
    })->name('support-show');
    
    Route::get('manage-support-faq', 'SupportAboutFaqController@manageFaqSupport')->name('support-manage-fq');
    
    Route::get('create-about',function () {
        return view('about_us.create_about');
    })->name('show_about'); 
    

resources/views/comming-soon.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Aurum Solver | Coming Soon</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{{asset('images/icons/favicon.ico')}}" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendorfile/bootstrap/css/bootstrap.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendorfile/animate/animate.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('vendorfile/select2/select2.min.css')}}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/util.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/main.css')}}?ver=2">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- <link rel="stylesheet" href="{{asset('css/mm-vertical.css')}}"> -->
    <!--===============================================================================================-->
</head>

<body>
    <div class="bg-img1 size1 overlay1" style="background-image: url('images/bg01.jpg');">
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                    <li><a href="/about" class="nav-link text-white">About The Application</a></li> 
                    <li><a href="{{route('supports')}}" class="nav-link text-white">Support/FAQ</a></li> 
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <!-- @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif -->
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('dashboard') }}"
                                       >
                                        {{ __('dashboard') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>       
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            
                        @endguest
                        
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- <a href="/about" class="btn btn-custom-link">About The Application</a>
    <a href="{{url('/login')}}" class="btn btn-danger">login</a> -->
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 my-auto">
                    <div class="text-center">
					<a href="https://play.google.com/store/apps/details?id=com.app.aurum_solver.aurum_solver&hl=en&gl=US" title="click here" target="_black">
                        <div class="mobile">
                            <img src="{{asset('images/mobile-removebg-preview.png')}}" alt="" class="mobi">
                            <img src="{{asset('images/logo-remove.png')}}" alt="" class="logo">
                        </div>
                    </a>
					</div>
                </div>
                <div class="col-lg-8 col-md-12 my-auto">
                    <div class="">
                        <p class="txt-center l1-txt1">
                            Our Mobile Application is <br><span class="l1-txt2">Under Development.</span><br>COMMING
                            SOON!
                        </p>
                    </div>
                    <div class="row cd100">
                        <div class="col-md-3 col-6">
                            <div class="flex-col-c-m size2 mx-auto bor1 m-b-20 m-l-10 m-r-10">
                                <span class="l1-txt3 p-b-9 days">35</span>
                                <span class="s1-txt2">Days</span>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="flex-col-c-m size2 mx-auto bor1 m-b-20 m-l-10 m-r-10">
                                <span class="l1-txt3 p-b-9 hours">17</span>
                                <span class="s1-txt2">Hours</span>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="flex-col-c-m size2 mx-auto bor1 m-b-20 m-l-10 m-r-10">
                                <span class="l1-txt3 p-b-9 minutes">50</span>
                                <span class="s1-txt2">Minutes</span>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="flex-col-c-m size2 mx-auto bor1 m-b-20 m-l-10 m-r-10">
                                <span class="l1-txt3 p-b-9 seconds">39</span>
                                <span class="s1-txt2">Seconds</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>





    <!--===============================================================================================-->
    <script src="{{asset('vendorfile/jquery/jquery-3.2.1.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendorfile/bootstrap/js/popper.js')}}"></script>
    <script src="{{asset('vendorfile/bootstrap/js/bootstrap.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendorfile/select2/select2.min.js')}}"></script>
    <!--===============================================================================================-->
    <script src="{{asset('vendorfile/countdowntime/moment.min.js')}}"></script>
    <script src="{{asset('vendorfile/countdowntime/moment-timezone.min.js')}}"></script>
    <script src="{{asset('vendorfile/countdowntime/moment-timezone-with-data.min.js')}}"></script>
    <script src="{{asset('vendorfile/countdowntime/countdowntime.js')}}"></script>

    <!-- <script src="{{asset('js/mm-animate.js')}}"></script> -->
    <script>
        start = new Date();
        end = new Date("2020-05-10")
        diff = new Date(end - start);
        days = diff/1000/60/60/24;
    $('.cd100').countdown100({
        /*Set Endtime here*/
        /*Endtime must be > current time*/
        endtimeYear: 0,
        endtimeMonth: 0,
        endtimeDate: days,
        endtimeHours: 18,
        endtimeMinutes: 0,
        endtimeSeconds: 0,
        timeZone: ""
        // ex:  timeZone: "America/New_York"
        //go to " http://momentjs.com/timezone/ " to get timezone
    });
    </script>
    <!--===============================================================================================-->
    <script src="vendor/tilt/tilt.jquery.min.js"></script>
    <script>
    $('.js-tilt').tilt({
        scale: 1.1
    })
    </script>
    <!--===============================================================================================-->
    <script src="js/main.js"></script>

</body>

</html>

resources/views/home.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <div class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <!-- <h5 class="font-weight-bold">@if(!empty($users)) {{$users}} @endif</h5> -->
                            <h5>Total App users</h5>
                        </div>
                        <div class="icon">
                        <i class="" aria-hidden="true">@if(!empty($users)) {{$users}} @endif</i>
                        </div>
                        <a href="{{route('dashboard.user.list')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <!-- <h5 class="font-weight-bold">@if(!empty($question)) {{$question}} @endif</h5> -->
                            <h5>Total Post Question</h5>
                        </div>
                        <div class="icon">
                            <i>@if(!empty($question)) {{$question}} @endif</i>
                        </div>
                        <a href="{{route('dashboard.all-question')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <!-- <h5 class="font-weight-bold">@if(!empty($answer)) {{$answer}} @endif</h5> -->
                            <h5>Assignment</h5>
                        </div>
                        <div class="icon">
                            <i class="">@if(!empty($answer)) {{$answer}} @endif</i>
                        </div>
                        <a href="{{route('dashboard.question')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>


                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h5>User Registrations</h5>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="{{route('dashboard.add')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i>
                              </a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">

                            <h5>Manage Category</h5>

                        </div>
                        <div class="icon">
                        <i class="fas fa-code-branch nav-icon "></i>
                        </div>
                        <a href="{{route('dashboard.category.manage')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <!-- second col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h5>Create Category</h5>

                        </div>
                        <div class="icon">
                        <i class="fas fa-code-branch nav-icon "></i>
                        </div>
                        <a href="{{route('dashboard.category.create')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>


                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>Create Quiz</h3>
                        </div>
                        <div class="icon">
                        <i class="icon fas fa-brain"></i>
                        </div>
                        <a href="{{route('dashboard.quiz.create')}}" class="small-box-footer">More info <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Main content -->
    <?php /*
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header border-0">
                <div class="d-flex justify-content-between">
                  <h3 class="card-title">Online Store Visitors</h3>
                  <a href="javascript:void(0);">View Report</a>
                </div>
              </div>
              <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">820</span>
                    <span>Visitors Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-Ass">
                      <i class="fas fa-arrow-up"></i> 12.5%
                    </span>
                    <span class="text-muted">Since last week</span>
                  </p>
                </div>
                <!-- /.d-flex -->

                <div class="position-relative mb-4">
                  <canvas id="visitors-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fas fa-square text-primary"></i> This Week
                  </span>

                  <span>
                    <i class="fas fa-square text-gray"></i> Last Week
                  </span>
                </div>
              </div>
            </div>
            <!-- /.card -->

           
            <!-- /.card -->
          </div>
          <!-- /.col-md-6 -->
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header border-0">
                <div class="d-flex justify-content-between">
                  <h3 class="card-title">Sales</h3>
                  <a href="javascript:void(0);">View Report</a>
                </div>
              </div>
              <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$18,230.00</span>
                    <span>Sales Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-Ass">
                      <i class="fas fa-arrow-up"></i> 33.1%
                    </span>
                    <span class="text-muted">Since last month</span>
                  </p>
                </div>
                <!-- /.d-flex -->

                <div class="position-relative mb-4">
                  <canvas id="sales-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fas fa-square text-primary"></i> This year
                  </span>

                  <span>
                    <i class="fas fa-square text-gray"></i> Last year
                  </span>
                </div>
              </div>
            </div>
            <!-- /.card -->

            
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    */ ?>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
@endsection

resources/views/mail.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello,Welcome to php mailer.</h1>
</body>
</html>