routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Render home
Route::get('/', 'SupportAboutFaqController@aboutUs');
Route::get('/home', function () {
    return view('/');
});

// render welcome page
Route::get('/welcome', function () {
    return view('welcome');
});
// render about page
// Route::get('/about', function () {
//     return view('about-us');
// });
Route::get('/about', 'SupportAboutFaqController@aboutUs')->name('about');
Route::get('/support', 'SupportAboutFaqController@displayFaq')->name('supports');
// Get Token
Route::post('/get-token', 'DataController@generateToken');
// Destroy Token
Route::post('/destroy-token', 'DataController@destroyToken');
Route::get('/reset-password', 'FirebaseController@resetPassword');
Route::get('/save', 'FirebaseController@savePassword')->name('setpassword');
// Route::get('/verify/email/{token}', 'Apps_UserController@mailVerify');
// Protected routes
Route::group(['middleware' => ['jwt.verify']], function() {
    Route::get('/apps/users/', 'Login_UserController@users');
    Route::post('/profile/update', 'profileUpdateController@userUpdate');
    Route::get('/user/{user_id}', 'profileUpdateController@userInfo');
    Route::post('/user/social/signup/','SocialController@socialSignup');
    Route::post('/user/login', 'Login_UserController@loginUser');
    Route::post('/user/register', 'Apps_UserController@appsUser');
    Route::get('/users/category/{category_id}', 'CategoryController@usersByCategory');
    Route::get('/category/{category_id}', 'CategoryController@category');
    Route::get('/user-profile/{id}', 'UsersProfilesController@userProfile');
   
    Route::post('/questions/ask/', 'questionContents@askQuestion');
    Route::post('/cancel/assignment/', 'assignmentPaymentController@cancelAssignment');
    Route::get('/questions/my/{user_id}', 'questionsController@askedQuestions');
    Route::get('/questions/all', 'questionsController@allQuestions');
    Route::get('/question/details/{id}', 'questionsController@getQuestion');
    Route::get('/questions/assigned/{user_id}', 'questionsController@assignedQuestion');
    Route::post('/questions/filter', 'filterAnswersController@filter');
    Route::post('/prepayments/to', 'transactionsController@prePayments');
    Route::get('/prepayments/my/{user_id}', 'PrepaymentRequestController@MyRequest');
    Route::post('/prepayments/request/update', 'PrepaymentRequestController@updateRequest');
    Route::get('/prepayments/requested/{user_id}', 'PrepaymentRequestController@PreRequested');
    Route::post('/assignment/pay', 'assignmentPaymentController@assignmentPayment');
    Route::post('/assignment/request/update', 'questionsController@assignmentUpdate');

    Route::get('/answer/all', 'ansQuestionsController@allAnswers');
    Route::post('/submit/assignment', 'ansQuestionsController@assignSubmit');
    Route::post('/submit/answer', 'ansQuestionsController@replyAns');
    Route::get('/answer/my/{user_id}', 'ansQuestionsController@myAnswers');                        
    Route::post('/answer/buy/', 'purchaseAnsController@purchaseAns');
    Route::get('/paid/answer/{user_id}', 'purchaseAnsController@MyBuyAnswer');
    Route::post('/delivery/update', 'assignmentPaymentController@deliveryUpdate');
    Route::get('/quizzes/ans', 'quizzesController@ansAtempts');
    Route::get('/user/quiz/{user_id}', 'quizzesController@ansAtempts');
    Route::get('/categories/all', 'CategoryController@categoryAll');
    Route::get('/category/all/{user_id}', 'CategoryController@usercategoryAll');
    Route::post('/category/quizzes', 'CategoryController@categoryQuizzes');
    Route::post('/answer/quiz', 'CategoryController@answerQuiz');
    Route::post('/quizzes/questions', 'quizzesController@quizAttempts');
    Route::post('/quizzes/attempt', 'replyQuizzeeController@quizAns');
    Route::post('/account/funds/add', 'addFundsController@addFunds'); 
    Route::post('/account/withdrawal', 'withdrawalAmountController@withdrawal');
    Route::get('/fetch/transaction/', 'transactionsController@fetch');
    Route::post('/chat/message', 'chatMessageController@chats');
    Route::get('/chat/reply', 'chatMessageController@preference');
    Route::get('/my/transaction/{id}', 'transactionsController@myTransaction');
    Route::get('/get/balance/{user_id}', 'transactionsController@balance');
    Route::post('/feedback/review', 'feedbacksController@feedback');
    Route::get('/search/{search_key}', 'filterAnswersController@search');
    Route::get('/feedback/my/{user_id}', 'feedbacksController@myFeedback');
    Route::post('/create/category', 'CategoryController@categoryCreate');
    Route::get('/app/user-profile/{registration_token}', 'Apps_UserController@getUser');
    Route::post('/ondemand/connect', 'AppUsersController@onDemandConnect');
    Route::post('/ondemand/disconnect', 'AppUsersController@onDemandDisconnect');
});    

Auth::routes();
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/logout', 'HomeController@logout')->name('home');
Route::group(['prefix'=>'dashboard','as'=>'dashboard.','middleware' => 'auth'], function(){
    Route::get('profile-update', 'AppUsersController@editProfile')->name('profile-update');
    Route::get('cancelled/assigment', 'AssignmentQuestionAnswerController@cancelledAssignment')->name('cancelled-assignment'); 
    Route::get('save', 'AppUsersController@savePaypal')->name('savepaypl'); 
    Route::get('assignment/questions', 'AssignmentQuestionAnswerController@assignment')->name('question');
    Route::get('refund-accept/{id}', 'AssigmentTransactionController@refundAccept')->name('refund-approve');
    Route::get('refund-reject/{id}', 'AssigmentTransactionController@refundReject')->name('refund-reject');
    Route::get('create/new/user', 'AppUsersController@createUser')->name('add');
    Route::get('cancelled/assignment', 'AssigmentTransactionController@cancellAssignmentList')->name('cancel-assignment');
    Route::post('refund/request/update', 'WithdrawalController@refundRequestUpdate')->name('refund-request.update');
    Route::post('withdrawal/request', 'WithdrawalController@withdrawalApprove')->name('withdrawal-request.update');
    Route::get('withdrawal/handle/{status}', 'WithdrawalController@withdrawalHandle')->name('withdrawal.handle');
    Route::get('refund/handle/{status}', 'WithdrawalController@refundHandle')->name('refund.handle');
    Route::get('withdrawal/request', 'AssigmentTransactionController@withdrawalRequest')->name('withdrawal');
    Route::get('profile', 'AppUsersController@myProfile')->name('myprofile');
    Route::get('my/transaction', 'AppUsersController@myTrasactionHistory')->name('mytransaction');

    Route::group(['prefix'=>'users','as'=>'user.'], function(){
        Route::get('update', 'AppUsersController@updateProfile')->name('update');
        Route::get('questions/edit/{id}', 'AssignmentQuestionAnswerController@editAllQuetion')->name('edit-post'); 
        Route::get('questions/delete/{id}', 'AssignmentQuestionAnswerController@deletePostQuestion')->name('delete-post'); 
        Route::get('delete/{id}', 'AppUsersController@deleteUser')->name('delete');
       
        Route::get('unblock/{id}', 'AppUsersController@unblock')->name('unblock');
        Route::get('block/{id}', 'AppUsersController@updateBlock')->name('toblock');
        Route::post('create', 'AppUsersController@createNewUser')->name('create-new-user');
        Route::post('create/dashboard', 'AppUsersController@createDasboardUser')->name('dash-new-user');
        Route::post('create/both-user', 'AppUsersController@createBothUser')->name('both-user');
        Route::get('/', 'AppUsersController@usersList')->name('list');
        Route::get('blocked', 'AppUsersController@blockUser')->name('block');
        Route::get('account', 'withdrawalAmountController@myAccount')->name('myaccount');
        Route::get('transaction', 'transactionsController@getTransactions')->name('transaction');
    });

    Route::group(['prefix'=>'category','as'=>'category.'], function(){
        Route::get('create',function(){
            return view('category.create-category');
        })->name('create');
        Route::get('edit/{id}', 'CreateCategoryController@edit')->name('edit');
        Route::get('create-category', 'CreateCategoryController@createCategory')->name('CreateCatogry');
        Route::get('/manage','CreateCategoryController@allCategory')->name('manage');
        Route::get('{id}', 'CreateCategoryController@delete')->name('delcategory');
        Route::get('update/{id}', 'CreateCategoryController@updateCategory')->name('update');        
    });

    Route::group(['prefix'=>'quiz','as'=>'quiz.'], function(){
        Route::get('/del/{id}','QuizCategoryController@delQuiz')->name('del');
        Route::get('/all/{id}','QuizCategoryController@allQuiz')->name('show');
        Route::get('/create','QuizCategoryController@quizzAllCreate')->name('create-quiz');
        Route::get('/manage','QuizCategoryController@allQuizzes')->name('manage-quiz');
        Route::get('create/', 'QuizCategoryController@createQuiz')->name('create');
    });

    Route::get('questions', 'AssignmentQuestionAnswerController@allQuestionAnswer')->name('all-question');
    
    Route::get('create/faq',function () {
        return view('support_faq.create_faq');
    })->name('support-show');
    
    Route::get('manage-support-faq', 'SupportAboutFaqController@manageFaqSupport')->name('support-manage-fq');
    
    Route::get('create-about',function () {
        return view('about_us.create_about');
    })->name('show_about'); 
    

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //fetch all data from backend
    protected $fillable = ['subjects'];
    protected $table = 'category';

    public function quizQuestions()
    {
        return $this->hasMany('App\Quizze','category_id','id');
    }

    /***
    	@Get category quiz count
    **/
 	public function quizCount()
    {	
        return $this->quizQuestions()->count();
    }

 	/***
    	@categoryQuiz quiz answer for user
    **/
    public function attemptHistory()
    {
        return $this->hasMany('App\Quiz_answer','category_id','id');
    }

    public function categoryQuiz()
    {
        return $this->hasMany('App\Quizze','category_id','id');
    }
    public function totalQuiz()
    {
        return $this->hasMany('App\Quizze','category_id','id');
    }
}

resources/views/category/create-category.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Create Category</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Category</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">

                    <div class="row centered-form justify-content-center">
                        <div class="col-xs-12 col-sm-8 col-md-6 ">
                            <div class="panel panel-default">
                                <div class="panel-heading">

                                    <h3 class="panel-title">Create New Category <span id="per_alert" class="text-danger"></span></h3>
                                </div>
                                <div class="jumbotron">
                                <div class="panel-body">
                                    <form action="{{route('dashboard.category.CreateCatogry')}}" id="form" role="form">
                                        {{@csrf_field()}}
                                        <div class="form-group">
                                            <label for="category_name">Category Name</label>
                                            <input autocomplete="off" id="category_name" name="category_name" type="text"
                                                class="form-control input-sm" placeholder="Category Name">
                                        </div>

                                        <div class="form-group">
                                            <label for="duration_time">Duration</label>
                                            <input autocomplete="off" type="number" id="duration_time" name="duration_time"
                                                class="form-control input-sm" placeholder="Duration">
                                        </div>

                                        <div class="form-group">
                                            <label for="duration_time">Duration</label>
                                            <input type="text" autocomplete="off" id="pass_percent" name="pass_percent"
                                                class="form-control input-sm" placeholder="Minimum Percentage">
                                        </div>
                                        <input type="submit" value="Create" class="btn btn-info btn-block">
                                    </form>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
@if(Session::has('message'))
var type = "{{ Session::get('alert-type', 'info') }}";
switch (type) {
    case 'info':
        flasher.info("{{ Session::get('message') }}");
        break;

    case 'warning':
        flasher.warning("{{ Session::get('message') }}");
        break;

    case 'success':
        flasher.success("{{ Session::get('message') }}");
        break;

    case 'error':
        flashser.error("{{ Session::get('message') }}");
        break;
}
@endif

$(document).ready(function() {
    let rowIndex = 0;
    $("#AddRow").click(function() {
        $('#maintable tr:last').after(`<tr>
        <td><input name="category_name${rowIndex++}" type="text" class="form-control"></td>
        <td><input type="text" name="duration_time${rowIndex++}" class="form-control"></td>
        <td><input type="text" name="pass_percent${rowIndex++}" class="form-control"></td>
        <td><button type="button"id="delete" onclick="deleteRows()"><i class="far fa-trash-alt"></i></button></td>
        </tr>`);
    });
});
$('#pass_percent').keyup(function() {
    if ($(this).val() > 100) {
        $('#per_alert').addClass("alert").text('Percentage not be more than 100!').show().fadeOut(
            3000);
        $(this).val('100');
    } else if ($(this).val() < 0) {
        $('#per_alert').addClass("alert").text('Percentage not be less than 0!').show().fadeOut(
            3000);
        $(this).val('100');
    }
});
$("#pass_percent").on("input", function(evt) {
    var self = $(this);
    self.val(self.val().replace(/[^\d].+/, ""));
    if ((evt.which < 48 || evt.which > 57)) 
     {
	   evt.preventDefault();
       $('#per_alert').addClass("alert").text('Only number is valid!').show().fadeOut(1000);
     }
 });
function deleteRows() {
    // event.target will be the input element.
    var td = event.target.parentNode;
    var tr = td.parentNode; 
    tr.parentNode.removeChild(tr);
}
</script>
@endsection

resources/views/category/manage-category.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Manage Category</h1>
                    @if (session('update'))
                    <div class="alert alert-warning" role="alert">
                        <h1>{{session('update')}}</h1>
                    </div>
                    @endif
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Category</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="card-body table-responsive p-0">
                                    <table id="dtHorizontalExample" class="table table-striped table-bordered"
                                        cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>CATEGORY</th>
                                                <th>DURATION</th>
                                                <th>PASSING PERCENTAGE</th>
                                                <th>ACTION</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                         
                                            @foreach($data as $category)

                                            <tr>
                                                <td>{{$category->id}}</td>
                                                <td>{{$category->subjects}}</td>
                                                <td>{{$category->duration}} min</td>
                                                <td>{{$category->min_percent}} %</td>
                                                <td>
                                                    <a href="{{route('dashboard.category.edit',['id'=>$category->id])}}"
                                                        class="btn btn-success"><i class="far fa-edit"></i>
                                                    </a>

                                                    {{-- <a href="{{route('dashboard.category.delcategory',['id'=>$category->id])}}"
                                                        onclick="return confirm('Are you sure ? to delete!')" class="btn btn-danger">
                                                        <i class="far fa-trash-alt"></i>
                                                    </a> --}}

                                                    <a href="" class="btn btn-danger delete-btn" data-id="{{ $category->id }}">
                                                        <i class="far fa-trash-alt"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- modal -->
    <div class="bs-example">
        <!-- Button HTML (to Trigger Modal) -->
        <!-- <input type="button" class="btn btn-lg btn-primary launch-modal" value="Add"> -->

        <!-- Modal HTML -->
        <div id="myModal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h6>Update Category</h6>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                    </div>
                    <div class="modal-body">
                        <form action="" class="shadow-lg p-3">
                            <div class="form-group">
                                <label for="name_category">Category Name</label>
                                <input type="text" name="name_category" class="form-control" id="name_category">
                            </div>
                            <div class="form-group">
                                <label for="duration_time">Duration</label>
                                <input type="text" name="duration_time" class="form-control" id="duration_time">
                            </div>
                            <div class="form-group">
                                <label for="passing_marks">Passing Percentage</label>
                                <input type="text" name="passing_marks" class="form-control" id="passing_marks">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- modal end -->
    
    <script>
        $('#dtHorizontalExample').DataTable();
        $(document).ready(function() {
            // @if(Session::has('message'))
            // var type = "{{Session::get('alert-type','info')}}"
            // switch (type) {
            //     case 'info':
            //         toastr.info("{{ Session::get('message') }}");
            //         break;
            //     case 'success':
            //         toastr.success("{{ Session::get('message') }}");
            //         break;
            //     case 'warning':
            //         toastr.warning("{{ Session::get('message') }}");
            //         break;
            //     case 'error':
            //         toastr.error("{{ Session::get('message') }}");
            //         break;
            // }
            // @endif
        });
    </script>

    {{-- delete-category --}}
    <script>
        $(document).ready(function(){
            $('.btn-danger').on('click', function(e) {
                e.preventDefault();
                var userId = $(this).data('id'); 
                swal({
                    title: "Are you sure? to delete!",
                    text: "Once deleted, you will not be able to recover this data!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                }).then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            type: 'GET',
                            url: '{{ route('dashboard.category.delcategory', ':id') }}'.replace(':id', userId),
                            data: {
                                _token: '{{ csrf_token() }}',
                            },
                            success: function(response) {
                                if (response.success) {
                                    swal("Success!", "Successfully deleted!", "success")
                                    .then(function() {
                                        flasher.success('Successfully deleted!');
                                        setTimeout(() => {
                                            location.reload();
                                        }, 2000);
                                    });
                                } else {
                                    swal("Error!", "An error occurred while deleting the category.", "error");
                                }
                            },
                            error: function() {
                                swal("Error!", "An error occurred while deleting the category.", "error");
                            }
                        });
                    }
                });
            });
        });
    </script>
    @endsection

resources/views/category/update.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Update Category</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Update</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            <div class="row justify-content-center">
                                <div class="col-lg-6">

                                    <form action="{{route('dashboard.category.update',['id'=>$data->id])}}" class="shadow-lg p-3">
                                        <div class="form-group">
                                            <input type="hidden" name="id" class="form-control" value="{{$data->id}}"
                                                id="name_category">
                                            <label for="name_category">Category Name</label>
                                            <input type="text" name="name_category" class="form-control"
                                                value="{{$data->subjects}}" id="name_category">
                                        </div>
                                        <div class="form-group">
                                            <label for="duration_time">Duration <span id="duration"></span></label>
                                            <input type="text" value=" {{$data->duration}} " name="duration_time"
                                                class="form-control  " id="duration_time">
                                        </div>
                                        <div class="form-group">
                                            <label for="passing_marks">Passing Percentage <span class="alert_err"id="passing"></span></label>
                                            <input type="text" value="{{$data->min_percent}}" name="passing_marks"
                                                class="form-control numbervalidation" id="passing_marks">
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{{url('/dashboard/category/manage')}}" class="btn btn-danger">
                                                Cancel
                                            </a>
                                            <button type="submit" name="submit" class="btn btn-primary">Save
                                                changes
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
@if(Session::has('message'))
var type = "{{Session::get('alert-type','info')}}"
switch (type) {
    case 'info':
        flasher.info("{{ Session::get('message') }}");
        break;
    case 'success':
        flasher.success("{{ Session::get('message') }}");
        break;
    case 'warning':
        flasher.warning("{{ Session::get('message') }}");
        break;
    case 'error':
        flasher.error("{{ Session::get('message') }}");
        break;
}
@endif

$('#passing_marks').keyup(function() {
    if ($(this).val() > 100) {
        $('#passing').addClass("alert").text('Percentage not be more than 100!').show().fadeOut(
            3000);
        $(this).val('100');
    } else if ($(this).val() < 0) {
        $('#passing').addClass("alert").text('Percentage not be less than 0!').show().fadeOut(
            3000);
        $(this).val('100');
    }

});
$(".numbervalidation").on("input", function(evt) {
    var self = $(this);
    self.val(self.val().replace(/[^\d].+/, ""));
    if ((evt.which < 48 || evt.which > 57)) 
     {
	   evt.preventDefault();
       $('.alert_err').addClass("alert").text('Only number is valid!').show().fadeOut(1000);
     }
 });
 $("#duration_time").on("input", function(evt) {
    var self = $(this);
    self.val(self.val().replace(/[^\d].+/, ""));
    if ((evt.which < 48 || evt.which > 57)) 
     {
	   evt.preventDefault();
       $('#duration').addClass("alert").text('Only number is valid!').show().fadeOut(1000);
     }
 });
</script>

@endsection