routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Render home
Route::get('/', 'SupportAboutFaqController@aboutUs');
Route::get('/home', function () {
    return view('/');
});

// render welcome page
Route::get('/welcome', function () {
    return view('welcome');
});
// render about page
// Route::get('/about', function () {
//     return view('about-us');
// });
Route::get('/about', 'SupportAboutFaqController@aboutUs')->name('about');
Route::get('/support', 'SupportAboutFaqController@displayFaq')->name('supports');
// Get Token
Route::post('/get-token', 'DataController@generateToken');
// Destroy Token
Route::post('/destroy-token', 'DataController@destroyToken');
Route::get('/reset-password', 'FirebaseController@resetPassword');
Route::get('/save', 'FirebaseController@savePassword')->name('setpassword');
// Route::get('/verify/email/{token}', 'Apps_UserController@mailVerify');
// Protected routes
Route::group(['middleware' => ['jwt.verify']], function() {
    Route::get('/apps/users/', 'Login_UserController@users');
    Route::post('/profile/update', 'profileUpdateController@userUpdate');
    Route::get('/user/{user_id}', 'profileUpdateController@userInfo');
    Route::post('/user/social/signup/','SocialController@socialSignup');
    Route::post('/user/login', 'Login_UserController@loginUser');
    Route::post('/user/register', 'Apps_UserController@appsUser');
    Route::get('/users/category/{category_id}', 'CategoryController@usersByCategory');
    Route::get('/category/{category_id}', 'CategoryController@category');
    Route::get('/user-profile/{id}', 'UsersProfilesController@userProfile');
   
    Route::post('/questions/ask/', 'questionContents@askQuestion');
    Route::post('/cancel/assignment/', 'assignmentPaymentController@cancelAssignment');
    Route::get('/questions/my/{user_id}', 'questionsController@askedQuestions');
    Route::get('/questions/all', 'questionsController@allQuestions');
    Route::get('/question/details/{id}', 'questionsController@getQuestion');
    Route::get('/questions/assigned/{user_id}', 'questionsController@assignedQuestion');
    Route::post('/questions/filter', 'filterAnswersController@filter');
    Route::post('/prepayments/to', 'transactionsController@prePayments');
    Route::get('/prepayments/my/{user_id}', 'PrepaymentRequestController@MyRequest');
    Route::post('/prepayments/request/update', 'PrepaymentRequestController@updateRequest');
    Route::get('/prepayments/requested/{user_id}', 'PrepaymentRequestController@PreRequested');
    Route::post('/assignment/pay', 'assignmentPaymentController@assignmentPayment');
    Route::post('/assignment/request/update', 'questionsController@assignmentUpdate');

    Route::get('/answer/all', 'ansQuestionsController@allAnswers');
    Route::post('/submit/assignment', 'ansQuestionsController@assignSubmit');
    Route::post('/submit/answer', 'ansQuestionsController@replyAns');
    Route::get('/answer/my/{user_id}', 'ansQuestionsController@myAnswers');                        
    Route::post('/answer/buy/', 'purchaseAnsController@purchaseAns');
    Route::get('/paid/answer/{user_id}', 'purchaseAnsController@MyBuyAnswer');
    Route::post('/delivery/update', 'assignmentPaymentController@deliveryUpdate');
    Route::get('/quizzes/ans', 'quizzesController@ansAtempts');
    Route::get('/user/quiz/{user_id}', 'quizzesController@ansAtempts');
    Route::get('/categories/all', 'CategoryController@categoryAll');
    Route::get('/category/all/{user_id}', 'CategoryController@usercategoryAll');
    Route::post('/category/quizzes', 'CategoryController@categoryQuizzes');
    Route::post('/answer/quiz', 'CategoryController@answerQuiz');
    Route::post('/quizzes/questions', 'quizzesController@quizAttempts');
    Route::post('/quizzes/attempt', 'replyQuizzeeController@quizAns');
    Route::post('/account/funds/add', 'addFundsController@addFunds'); 
    Route::post('/account/withdrawal', 'withdrawalAmountController@withdrawal');
    Route::get('/fetch/transaction/', 'transactionsController@fetch');
    Route::post('/chat/message', 'chatMessageController@chats');
    Route::get('/chat/reply', 'chatMessageController@preference');
    Route::get('/my/transaction/{id}', 'transactionsController@myTransaction');
    Route::get('/get/balance/{user_id}', 'transactionsController@balance');
    Route::post('/feedback/review', 'feedbacksController@feedback');
    Route::get('/search/{search_key}', 'filterAnswersController@search');
    Route::get('/feedback/my/{user_id}', 'feedbacksController@myFeedback');
    Route::post('/create/category', 'CategoryController@categoryCreate');
    Route::get('/app/user-profile/{registration_token}', 'Apps_UserController@getUser');
    Route::post('/ondemand/connect', 'AppUsersController@onDemandConnect');
    Route::post('/ondemand/disconnect', 'AppUsersController@onDemandDisconnect');
});    

Auth::routes();
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/logout', 'HomeController@logout')->name('home');
Route::group(['prefix'=>'dashboard','as'=>'dashboard.','middleware' => 'auth'], function(){
    Route::get('profile-update', 'AppUsersController@editProfile')->name('profile-update');
    Route::get('cancelled/assigment', 'AssignmentQuestionAnswerController@cancelledAssignment')->name('cancelled-assignment'); 
    Route::get('save', 'AppUsersController@savePaypal')->name('savepaypl'); 
    Route::get('assignment/questions', 'AssignmentQuestionAnswerController@assignment')->name('question');
    Route::get('refund-accept/{id}', 'AssigmentTransactionController@refundAccept')->name('refund-approve');
    Route::get('refund-reject/{id}', 'AssigmentTransactionController@refundReject')->name('refund-reject');
    Route::get('create/new/user', 'AppUsersController@createUser')->name('add');
    Route::get('cancelled/assignment', 'AssigmentTransactionController@cancellAssignmentList')->name('cancel-assignment');
    Route::post('refund/request/update', 'WithdrawalController@refundRequestUpdate')->name('refund-request.update');
    Route::post('withdrawal/request', 'WithdrawalController@withdrawalApprove')->name('withdrawal-request.update');
    Route::get('withdrawal/handle/{status}', 'WithdrawalController@withdrawalHandle')->name('withdrawal.handle');
    Route::get('refund/handle/{status}', 'WithdrawalController@refundHandle')->name('refund.handle');
    Route::get('withdrawal/request', 'AssigmentTransactionController@withdrawalRequest')->name('withdrawal');
    Route::get('profile', 'AppUsersController@myProfile')->name('myprofile');
    Route::get('my/transaction', 'AppUsersController@myTrasactionHistory')->name('mytransaction');

    Route::group(['prefix'=>'users','as'=>'user.'], function(){
        Route::get('update', 'AppUsersController@updateProfile')->name('update');
        Route::get('questions/edit/{id}', 'AssignmentQuestionAnswerController@editAllQuetion')->name('edit-post'); 
        Route::get('questions/delete/{id}', 'AssignmentQuestionAnswerController@deletePostQuestion')->name('delete-post'); 
        Route::get('delete/{id}', 'AppUsersController@deleteUser')->name('delete');
       
        Route::get('unblock/{id}', 'AppUsersController@unblock')->name('unblock');
        Route::get('block/{id}', 'AppUsersController@updateBlock')->name('toblock');
        Route::post('create', 'AppUsersController@createNewUser')->name('create-new-user');
        Route::post('create/dashboard', 'AppUsersController@createDasboardUser')->name('dash-new-user');
        Route::post('create/both-user', 'AppUsersController@createBothUser')->name('both-user');
        Route::get('/', 'AppUsersController@usersList')->name('list');
        Route::get('blocked', 'AppUsersController@blockUser')->name('block');
        Route::get('account', 'withdrawalAmountController@myAccount')->name('myaccount');
        Route::get('transaction', 'transactionsController@getTransactions')->name('transaction');
    });

    Route::group(['prefix'=>'category','as'=>'category.'], function(){
        Route::get('create',function(){
            return view('category.create-category');
        })->name('create');
        Route::get('edit/{id}', 'CreateCategoryController@edit')->name('edit');
        Route::get('create-category', 'CreateCategoryController@createCategory')->name('CreateCatogry');
        Route::get('/manage','CreateCategoryController@allCategory')->name('manage');
        Route::get('{id}', 'CreateCategoryController@delete')->name('delcategory');
        Route::get('update/{id}', 'CreateCategoryController@updateCategory')->name('update');        
    });

    Route::group(['prefix'=>'quiz','as'=>'quiz.'], function(){
        Route::get('/del/{id}','QuizCategoryController@delQuiz')->name('del');
        Route::get('/all/{id}','QuizCategoryController@allQuiz')->name('show');
        Route::get('/create','QuizCategoryController@quizzAllCreate')->name('create-quiz');
        Route::get('/manage','QuizCategoryController@allQuizzes')->name('manage-quiz');
        Route::get('create/', 'QuizCategoryController@createQuiz')->name('create');
    });

    Route::get('questions', 'AssignmentQuestionAnswerController@allQuestionAnswer')->name('all-question');
    
    Route::get('create/faq',function () {
        return view('support_faq.create_faq');
    })->name('support-show');
    
    Route::get('manage-support-faq', 'SupportAboutFaqController@manageFaqSupport')->name('support-manage-fq');
    
    Route::get('create-about',function () {
        return view('about_us.create_about');
    })->name('show_about'); 
    

app/User.php
<?php

    namespace App;

    use Illuminate\Notifications\Notifiable;
    use Illuminate\Foundation\Auth\User as Authenticatable;
    // use Tymon\JWTAuth\Contracts\JWTSubject;
    use Spatie\Permission\Traits\HasRoles;

    // class User extends Authenticatable implements JWTSubject
    class User extends Authenticatable
    {
        use Notifiable; use HasRoles;

        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'name', 'email', 'password', 'access_token',
        ];

        /**
         * The attributes that should be hidden for arrays.
         *
         * @var array
         */
        protected $hidden = [
            'password', 'remember_token',
        ];

        public function getJWTIdentifier()
        {
            return $this->getKey();
        }
        public function getJWTCustomClaims()
        {
            return [];
        }
    }

app/Http/Controllers/UserController.php
<?php

// namespace App\Http\Controllers;

// use App\User;
// use Illuminate\Http\Request;
// use Illuminate\Support\Facades\Hash;
// use Illuminate\Support\Facades\Validator;
// // use JWTAuth;
// // use Tymon\JWTAuth\Exceptions\JWTException;
// use Illuminate\Support\Facades\DB;


// class UserController extends Controller
// {
//     public function authenticate(Request $request)
//     {
//         $credentials = $request->only('email', 'password');

//         try {
//             if (! $token = JWTAuth::attempt($credentials)) {
//                 return response()->json(['error' => 'invalid_credentials'], 400);
//             }
//         } catch (JWTException $e) {
//             return response()->json(['error' => 'could_not_create_token'], 500);
//         }

//         return response()->json(compact('token'));
//     }

//     public function register(Request $request)
//     {
//         $validator = Validator::make($request->all(), [
//             'name' => 'required|string|max:255',
//             'email' => 'required|string|email|max:255|unique:users',
//             'password' => 'required|string|min:6|confirmed',
//         ]);

//         if($validator->fails()){
//             return response()->json($validator->errors()->toJson(), 400);
//         }

//         $user = User::create([
//             'name' => $request->get('name'),
//             'email' => $request->get('email'),
//             'password' => Hash::make($request->get('password')),
//         ]);

//         $token = JWTAuth::fromUser($user);

//         return response()->json(compact('user','token'),201);
//     }

//     public function getAuthenticatedUser()
//     {
//         try {
//             if (! $user = JWTAuth::parseToken()->authenticate()) {
//                 return response()->json(['user_not_found'], 404);
//             }
//         } 
//         catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
//             return response()->json(['token_expired'], $e->getStatusCode());

//         }
//         catch (Tymon\JWTAuth\Exceptions\TokenInvalidException $e) {
//             return response()->json(['token_invalid'], $e->getStatusCode());
//         } 
//         catch (Tymon\JWTAuth\Exceptions\JWTException $e) {
//             return response()->json(['token_absent'], $e->getStatusCode());

//         }
//         return response()->json(compact('user'));
//     }
// }

namespace App\Http\Controllers;
use App\User; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function authenticate(Request $request)
    {
        $credentials = $request->only('email', 'password');

        if (!Auth::attempt($credentials)) {
            return response()->json(['error' => 'invalid_credentials'], 401);
        }

        $user = Auth::user();
        $token = $user->createToken('authToken')->plainTextToken; 

        return response()->json(['token' => $token], 200);
    }

    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        if ($validator->fails()) {
            return response()->json($validator->errors(), 400);
        }

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);

        $token = $user->createToken('authToken')->plainTextToken;
        return response()->json(['user' => $user, 'token' => $token], 201);
    }

    public function getAuthenticatedUser(Request $request)
    {
        $user = Auth::user();

        if (!$user) {
            return response()->json(['error' => 'user_not_found'], 404);
        }

        return response()->json(['user' => $user], 200);
    }
}

resources/views/user/app-user.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Users</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active">User list</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="card-body table-responsive p-0">
                                    <table id="userTable" class="table table-striped" cellspacing="0"
                                        width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>PROFILE</th>
                                                <th>EMAIL-ID</th>
                                                <th>FIRST NAME</th>
                                                <th>USER ROLE</th>
                                                <th>LAST LOGIN</th>
                                                <th>ACTION</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($data as $val)
                                            <tr>
                                                <td>{{$val->id}}</td>
                                                <td>
                                                    <div class="image">
                                                        <img src="{{isset($val->profile_pic)?$val->profile_pic:''}}"
                                                            class="img-circle elevation-2"
                                                            style="width:70px; height:70px;" alt="pic">
                                                    </div>
                                                </td>
                                                <td>{{$val->user_email}}</td>
                                                <td>{{isset($val->first_name)?$val->first_name:'N/A'}}</td>
                                                <td>{{isset($val->user_type)?$val->user_type:'N/A'}}</td>
                                                <td>{{isset($val->last_login)?$val->  last_login:'N/A'}}</td>
                                                <td class="d-flex">
                                                    {{-- <a href="{{route('dashboard.user.delete',['id'=>$val->id])}}"
                                                        class="btn btn-danger mr-1"
                                                        onclick="return confirm('Are you sure ? to delete')">
                                                        Delete
                                                    </a> --}}
                                                    <a href="" 
                                                    class="btn btn-danger mr-1" 
                                                    id="delete_user_{{ $val->id }}" data-id="{{ $val->id }}">
                                                        Delete
                                                    </a>
                                                    @if($val->is_active==1)
                                                    {{-- <a href="{{route('dashboard.user.toblock',['id'=>$val->id])}}"
                                                        class="btn btn-primary"
                                                        onclick="return confirm('Are you sure you want to block this user?')">
                                                        Block</a> --}}
                                                        <a href="javascript:void(0);"
                                                            class="btn btn-primary btn-primary1"
                                                           id="block_user_{{ $val->id }}" data-id="{{ $val->id }}">
                                                            Block
                                                        </a>
                                                    @else
                                                    {{-- <a href="{{route('dashboard.user.unblock',['id'=>$val->id])}}"
                                                        class="btn btn-success"
                                                        onclick="return confirm('Are you sure you want to acivate this user?')">
                                                        Unblock</a> --}}
                                                        <a href="javascript:void(0);"
                                                            class="btn btn-success btn-success1"
                                                           id="unblock_user_{{ $val->id }}" data-id="{{ $val->id }}">
                                                            Unblock
                                                        </a>
                                                    @endif
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
   $('#userTable').DataTable({
        "order": [[ 0, "desc" ]]
    });
</script>
{{-- delete user and block & unblock--}}
<script>
    $(document).ready(function(){
        // delete user
        $('.btn-danger').on('click', function(e) {
            e.preventDefault();
            var userId = $(this).data('id'); 
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this data!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'GET',
                        url: '{{ route('dashboard.user.delete', ':id') }}'.replace(':id', userId),
                        data: {
                            _token: '{{ csrf_token() }}',
                        },
                        success: function(response) {
                            if (response.success) {
                                swal("Success!", "User has been deleted.", "success")
                                .then(function() {
                                    flasher.success('User deleted');
                                    setTimeout(() => {
                                        location.reload();
                                    }, 2000);
                                });
                            } else {
                                swal("Error!", "An error occurred while deleting the user.", "error");
                            }
                        },
                        error: function() {
                            swal("Error!", "An error occurred while deleting the user.", "error");
                        }
                    });
                }
            });
        });

        // user block & unblock
        $('.btn-primary1, .btn-success1').on('click', function(e) {
            e.preventDefault();
            var userId = $(this).data('id'); 
            var isBlocking = $(this).hasClass('btn-primary');
            swal({
                title: "Are you sure?",
                text: isBlocking ? "You want to block this user?" : "You want to activate this user?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willProceed) => {
                if (willProceed) {
                    $.ajax({
                        type: 'GET',
                        url: isBlocking
                            ? '{{ route('dashboard.user.toblock', ':id') }}'.replace(':id', userId)
                            : '{{ route('dashboard.user.unblock', ':id') }}'.replace(':id', userId),
                        data: {
                            _token: '{{ csrf_token() }}',
                        },
                        success: function(response) {
                            if (response.success) {
                                swal("Success!", isBlocking ? "User has been blocked!" : "User has been activated!", "success")
                                .then(function() {
                                    flasher.success(isBlocking ? 'User has been blocked!' : 'User has been activated!');
                                    setTimeout(() => {
                                        location.reload();
                                    }, 2000);
                                });
                            } else {
                                swal("Error!", "An error occurred while updating the user status.", "error");
                            }
                        },
                        error: function() {
                            swal("Error!", "An error occurred while updating the user status.", "error");
                        }
                    });
                }
            });
        });
    });
</script>
@endsection

 

resources/views/user/block-user.blade.php
@extends('layouts.master')
@section('content')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Users</h1>
                    @if (session('update'))
                    <div class="alert alert-warning" role="alert">
                        <h1>{{session('update')}}</h1>
                    </div>
                    @endif
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">User list</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                         
                       
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="card-body table-responsive p-0">
                                    <table id="userTable" class="table table-striped table-bordered" cellspacing="0"
                                        width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>PROFILE</th>
                                                <th>EMAIL-ID</th>
                                                <th>FIRST NAME</th>
                                                <th>USER ROLE</th>
                                                <th>LAST LOGIN</th>
                                                <th>ACTION</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($data as $val)
                                            <tr>
                                                <td>{{$val->id}}</td>
                                                <td>
                                                    <div class="image">
                                                        <img src="{{isset($val->profile_pic)?$val->profile_pic:''}}"
                                                            class="img-circle elevation-2"
                                                            style="width:70px; height:70px;" alt="pic">
                                                    </div>
                                                </td>
                                                <td>{{$val->user_email}}</td>
                                                <td>{{isset($val->first_name)?$val->first_name:'N/A'}}</td>
                                                <td>{{isset($val->user_type)?$val->user_type:'N/A'}}</td>
                                                <td>{{isset($val->last_login)?$val->  last_login:'N/A'}}</td>
                                                <td>
                                                    <a href="{{route('dashboard.user.unblock',['id'=>$val->id])}}" class="btn btn-success"
                                                        onclick="return confirm('Are you sure you want to acivate this user?')">
                                                        Unblock</a>
                                                    <a href="{{route('dashboard.user.delete',['id'=>$val->id])}}" class="btn btn-danger"
                                                        onclick="return confirm('Are you sure ? to delete')">
                                                        Delete</a>
                                                   
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>

                                </div>

                            </div>
                            <!-- /.d-flex -->
                        </div>
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->


    <script>
   @if(Session::has('message'))
    var type = "{{Session::get('alert-type','info')}}"
    switch (type) {
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;
        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
    @endif
    
    $('#userTable').DataTable({
        "order": [[ 0, "desc" ]]
    });

    $(document).ready(function() {

    });
    </script>
    @endsection