routes/web.php
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Render home
Route::get('/', 'SupportAboutFaqController@aboutUs');
Route::get('/home', function () {
    return view('/');
});

// render welcome page
Route::get('/welcome', function () {
    return view('welcome');
});
// render about page
// Route::get('/about', function () {
//     return view('about-us');
// });
Route::get('/about', 'SupportAboutFaqController@aboutUs')->name('about');
Route::get('/support', 'SupportAboutFaqController@displayFaq')->name('supports');
// Get Token
Route::post('/get-token', 'DataController@generateToken');
// Destroy Token
Route::post('/destroy-token', 'DataController@destroyToken');
Route::get('/reset-password', 'FirebaseController@resetPassword');
Route::get('/save', 'FirebaseController@savePassword')->name('setpassword');
// Route::get('/verify/email/{token}', 'Apps_UserController@mailVerify');
// Protected routes
Route::group(['middleware' => ['jwt.verify']], function() {
    Route::get('/apps/users/', 'Login_UserController@users');
    Route::post('/profile/update', 'profileUpdateController@userUpdate');
    Route::get('/user/{user_id}', 'profileUpdateController@userInfo');
    Route::post('/user/social/signup/','SocialController@socialSignup');
    Route::post('/user/login', 'Login_UserController@loginUser');
    Route::post('/user/register', 'Apps_UserController@appsUser');
    Route::get('/users/category/{category_id}', 'CategoryController@usersByCategory');
    Route::get('/category/{category_id}', 'CategoryController@category');
    Route::get('/user-profile/{id}', 'UsersProfilesController@userProfile');
   
    Route::post('/questions/ask/', 'questionContents@askQuestion');
    Route::post('/cancel/assignment/', 'assignmentPaymentController@cancelAssignment');
    Route::get('/questions/my/{user_id}', 'questionsController@askedQuestions');
    Route::get('/questions/all', 'questionsController@allQuestions');
    Route::get('/question/details/{id}', 'questionsController@getQuestion');
    Route::get('/questions/assigned/{user_id}', 'questionsController@assignedQuestion');
    Route::post('/questions/filter', 'filterAnswersController@filter');
    Route::post('/prepayments/to', 'transactionsController@prePayments');
    Route::get('/prepayments/my/{user_id}', 'PrepaymentRequestController@MyRequest');
    Route::post('/prepayments/request/update', 'PrepaymentRequestController@updateRequest');
    Route::get('/prepayments/requested/{user_id}', 'PrepaymentRequestController@PreRequested');
    Route::post('/assignment/pay', 'assignmentPaymentController@assignmentPayment');
    Route::post('/assignment/request/update', 'questionsController@assignmentUpdate');

    Route::get('/answer/all', 'ansQuestionsController@allAnswers');
    Route::post('/submit/assignment', 'ansQuestionsController@assignSubmit');
    Route::post('/submit/answer', 'ansQuestionsController@replyAns');
    Route::get('/answer/my/{user_id}', 'ansQuestionsController@myAnswers');                        
    Route::post('/answer/buy/', 'purchaseAnsController@purchaseAns');
    Route::get('/paid/answer/{user_id}', 'purchaseAnsController@MyBuyAnswer');
    Route::post('/delivery/update', 'assignmentPaymentController@deliveryUpdate');
    Route::get('/quizzes/ans', 'quizzesController@ansAtempts');
    Route::get('/user/quiz/{user_id}', 'quizzesController@ansAtempts');
    Route::get('/categories/all', 'CategoryController@categoryAll');
    Route::get('/category/all/{user_id}', 'CategoryController@usercategoryAll');
    Route::post('/category/quizzes', 'CategoryController@categoryQuizzes');
    Route::post('/answer/quiz', 'CategoryController@answerQuiz');
    Route::post('/quizzes/questions', 'quizzesController@quizAttempts');
    Route::post('/quizzes/attempt', 'replyQuizzeeController@quizAns');
    Route::post('/account/funds/add', 'addFundsController@addFunds'); 
    Route::post('/account/withdrawal', 'withdrawalAmountController@withdrawal');
    Route::get('/fetch/transaction/', 'transactionsController@fetch');
    Route::post('/chat/message', 'chatMessageController@chats');
    Route::get('/chat/reply', 'chatMessageController@preference');
    Route::get('/my/transaction/{id}', 'transactionsController@myTransaction');
    Route::get('/get/balance/{user_id}', 'transactionsController@balance');
    Route::post('/feedback/review', 'feedbacksController@feedback');
    Route::get('/search/{search_key}', 'filterAnswersController@search');
    Route::get('/feedback/my/{user_id}', 'feedbacksController@myFeedback');
    Route::post('/create/category', 'CategoryController@categoryCreate');
    Route::get('/app/user-profile/{registration_token}', 'Apps_UserController@getUser');
    Route::post('/ondemand/connect', 'AppUsersController@onDemandConnect');
    Route::post('/ondemand/disconnect', 'AppUsersController@onDemandDisconnect');
});    

Auth::routes();
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/logout', 'HomeController@logout')->name('home');
Route::group(['prefix'=>'dashboard','as'=>'dashboard.','middleware' => 'auth'], function(){
    Route::get('profile-update', 'AppUsersController@editProfile')->name('profile-update');
    Route::get('cancelled/assigment', 'AssignmentQuestionAnswerController@cancelledAssignment')->name('cancelled-assignment'); 
    Route::get('save', 'AppUsersController@savePaypal')->name('savepaypl'); 
    Route::get('assignment/questions', 'AssignmentQuestionAnswerController@assignment')->name('question');
    Route::get('refund-accept/{id}', 'AssigmentTransactionController@refundAccept')->name('refund-approve');
    Route::get('refund-reject/{id}', 'AssigmentTransactionController@refundReject')->name('refund-reject');
    Route::get('create/new/user', 'AppUsersController@createUser')->name('add');
    Route::get('cancelled/assignment', 'AssigmentTransactionController@cancellAssignmentList')->name('cancel-assignment');
    Route::post('refund/request/update', 'WithdrawalController@refundRequestUpdate')->name('refund-request.update');
    Route::post('withdrawal/request', 'WithdrawalController@withdrawalApprove')->name('withdrawal-request.update');
    Route::get('withdrawal/handle/{status}', 'WithdrawalController@withdrawalHandle')->name('withdrawal.handle');
    Route::get('refund/handle/{status}', 'WithdrawalController@refundHandle')->name('refund.handle');
    Route::get('withdrawal/request', 'AssigmentTransactionController@withdrawalRequest')->name('withdrawal');
    Route::get('profile', 'AppUsersController@myProfile')->name('myprofile');
    Route::get('my/transaction', 'AppUsersController@myTrasactionHistory')->name('mytransaction');

    Route::group(['prefix'=>'users','as'=>'user.'], function(){
        Route::get('update', 'AppUsersController@updateProfile')->name('update');
        Route::get('questions/edit/{id}', 'AssignmentQuestionAnswerController@editAllQuetion')->name('edit-post'); 
        Route::get('questions/delete/{id}', 'AssignmentQuestionAnswerController@deletePostQuestion')->name('delete-post'); 
        Route::get('delete/{id}', 'AppUsersController@deleteUser')->name('delete');
       
        Route::get('unblock/{id}', 'AppUsersController@unblock')->name('unblock');
        Route::get('block/{id}', 'AppUsersController@updateBlock')->name('toblock');
        Route::post('create', 'AppUsersController@createNewUser')->name('create-new-user');
        Route::post('create/dashboard', 'AppUsersController@createDasboardUser')->name('dash-new-user');
        Route::post('create/both-user', 'AppUsersController@createBothUser')->name('both-user');
        Route::get('/', 'AppUsersController@usersList')->name('list');
        Route::get('blocked', 'AppUsersController@blockUser')->name('block');
        Route::get('account', 'withdrawalAmountController@myAccount')->name('myaccount');
        Route::get('transaction', 'transactionsController@getTransactions')->name('transaction');
    });

    Route::group(['prefix'=>'category','as'=>'category.'], function(){
        Route::get('create',function(){
            return view('category.create-category');
        })->name('create');
        Route::get('edit/{id}', 'CreateCategoryController@edit')->name('edit');
        Route::get('create-category', 'CreateCategoryController@createCategory')->name('CreateCatogry');
        Route::get('/manage','CreateCategoryController@allCategory')->name('manage');
        Route::get('{id}', 'CreateCategoryController@delete')->name('delcategory');
        Route::get('update/{id}', 'CreateCategoryController@updateCategory')->name('update');        
    });

    Route::group(['prefix'=>'quiz','as'=>'quiz.'], function(){
        Route::get('/del/{id}','QuizCategoryController@delQuiz')->name('del');
        Route::get('/all/{id}','QuizCategoryController@allQuiz')->name('show');
        Route::get('/create','QuizCategoryController@quizzAllCreate')->name('create-quiz');
        Route::get('/manage','QuizCategoryController@allQuizzes')->name('manage-quiz');
        Route::get('create/', 'QuizCategoryController@createQuiz')->name('create');
    });

    Route::get('questions', 'AssignmentQuestionAnswerController@allQuestionAnswer')->name('all-question');
    
    Route::get('create/faq',function () {
        return view('support_faq.create_faq');
    })->name('support-show');
    
    Route::get('manage-support-faq', 'SupportAboutFaqController@manageFaqSupport')->name('support-manage-fq');
    
    Route::get('create-about',function () {
        return view('about_us.create_about');
    })->name('show_about'); 
    
    Route::get('edit-about/{id}', 'SupportAboutFaqController@editAbout')->name('edit_about'); 
    Route::get('delete-about/{id}', 'SupportAboutFaqController@delAbout')->name('del_about');   
    Route::get('manage-about', 'SupportAboutFaqController@manageAbout')->name('manage_about');

resources/views/quiz/create-quiz.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- @if (session('delete'))
                    <div class="alert alert-danger" id="success-alert">
                        <button type="button" class="close" data-dismiss="alert">x</button>
                        <strong>Success!</strong>
                        {{session('delete')}}
                    </div>
                    @endif
                    <h1 class="m-0 text-dark">Manage Quiz</h1> -->
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Quiz</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">

                        <div class="card-body">
                            <div class="d-flex">
                                <div class="card-body table-responsive p-0">
                                <table id="dtHorizontalExample" class="table table-striped table-bordered"
                                        cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>#ID</th>
                                                <th>Category Name </th>
                                                <th>Total Questions</th>
                                                <th class="text-center">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody id="maintable">
                                            <!-- {{print_r($data)}} -->
                                            @foreach($data as $key=>$val)
                                            <tr>
                                                <td>{{$val->id}}</td>
                                                <td>{{$val->subjects}}</td>

                                                <td>{{$val->total_quiz_count}}</td>
                                                <td class="text-center">
                                                    <a href="{{route('dashboard.quiz.create',['id'=>$val->subjects])}}" data-toggle="tooltip"
                                                        title="Create quiz!" data-placement="bottom"
                                                        class="btn btn-primary"><i class="fas fa-plus"></i></a>
                                                    <a href="/dashboard/quiz/edit/{{$val->id}}" class="btn btn-success"
                                                        data-placement="bottom" data-toggle="tooltip"
                                                        title="Update quiz"><i class="far fa-edit"></i></a>
                                                    <!-- <a href="/dashboard/quiz/list/{{$val->id}} "
                                                        class="btn btn-secondary" data-placement="bottom"
                                                        data-toggle="tooltip" title="Quiz"><i
                                                            class="fas fa-list"></i></a> -->
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>


                                </div>
                            </div>
                            <!-- /.d-flex -->
                        </div>
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div>
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
    <script>
    //   tostr alert
    $('tableId1').DataTable();
    @if(Session::has('message'))
    var type = "{{Session::get('alert-type','info')}}"
    switch (type) {
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;
        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
    @endif
    $('#dtHorizontalExample').DataTable();
    $(document).ready(function() {
        $('[data-toggle="tooltip"]').tooltip();
      
        $("#success-alert").hide(6000);
        $("#myWish").click(function showAlert() {
            $("#success-alert").alert();
            window.setTimeout(function() {
                $("#success-alert").alert('close');
            }, 2000);
        });

    });
    </script>
    @endsection

resources/views/quiz/manage-quiz.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Manage Quiz</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Quiz</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="card-body ">


                                    <table id="userTable" class="table table-striped table-bordered" cellspacing="0"
                                        width="100%">
                                        <thead class="bg-dark">
                                            <tr>
                                                <th># ID</th>
                                                <th>Category Name </th>
                                                <th>Total Quiz Available</th>

                                                <th class="text-center" style=" ">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody id="maintable">

                                            @foreach($data as $key=>$val)
                                            <td>{{$val->id}}</td>
                                            <td>{{$val->subjects}}</td>
                                            <td class="text-center">{{$val->total_quiz_count}}</td>

                                            <td class="text-center">
                                            <a href="{{route('dashboard.quiz.create')}}" class="btn btn-primary"><i
                                                        class="fa fa-plus"></i> add</a>
                                                @if($val->total_quiz_count > 0)
                                                <a href="{{route('dashboard.quiz.show',['id'=>$val->id])}}"
                                                    title="edit quiz" class="btn btn-dark" title="Show all quiz"><i
                                                        class="fa fa-eye"></i></a>
                                                <a href="/dashboard/quiz/edit/{{$val->id}}" title="edit quiz"
                                                    class="btn btn-success"><i class="far fa-edit"></i></a>
                                                <!-- <a href="/dashboard/delete/quiz/{{$val->id}}" class="btn btn-danger"
                                                        onclick="return confirm('Are you sure ? to delete')"><i
                                                            class="fas fa-trash"></i></a> -->
                                                @else
                                                <button disabled class="btn btn-danger"><i
                                                        class="fa fa-eye-slash"></i></button>
                                                <a href="" disabled class="btn btn-success"><i
                                                        class="far fa-edit"></i></a>
                                                
                                                <!-- <a href="/dashboard/delete/quiz/{{$val->id}}" class="btn btn-danger"
                                                    disabled onclick="return confirm('Are you sure ? to delete')"><i
                                                        class="fas fa-trash"></i></a> -->
                                                @endif

                                            </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>


                                </div>
                            </div>
                            <!-- /.d-flex -->
                        </div>
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
            </div>
        </div>
        <!-- /.row -->
        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <!-- <h4 class="modal-title">Modal Header</h4> -->
                    </div>
                    <div class="modal-body">
                        <table id="userTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>#ID</th>
                                    <th>Questions </th>
                                    <th>Option 1</th>
                                    <th>Option 2</th>
                                    <th>Option 3</th>
                                    <th>Option 4</th>
                                    <th style="width:120px;">Correct Option</th>
                                </tr>
                            </thead>
                        </table>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->
<!-- Modal view quiz -->
<!-- Trigger the modal with a button -->

<script>
@if(Session::has('message'))
var type = "{{Session::get('alert-type','info')}}"
switch (type) {
    case 'info':
        toastr.info("{{ Session::get('message') }}");
        break;
    case 'success':
        toastr.success("{{ Session::get('message') }}");
        break;
    case 'warning':
        toastr.warning("{{ Session::get('message') }}");
        break;
    case 'error':
        toastr.error("{{ Session::get('message') }}");
        break;
}
@endif
$(document).ready(function() {
    // $('#veiwQuiz').click(function(){
    //     var id=$('#veiwQuiz').val();
    //     alert(id);
    // });
    // $("#category_id").change(function() {
    //     var cat_id = $(this).val();
    //     //    $('#fetch').attr('href').append('/quiz/list/'+cat_id)
    //     $.ajax({
    //         type: "GET",
    //         url: "/quiz/list/" + cat_id,
    //         dataType   :'json',
    //         success: function(data){
    //             $('#total_questions').text(data.data);
    //             $.each(data, function(index, row) {

    //             })

    //         }
    //     });
    // });
    // table pagination
    // //   table responsive
    // $('#dtHorizontalExample').DataTable({
    //     "scrollX": true
    // });
    // $('.dataTables_length').addClass('bs-select');
    // $('#example').DataTable();
    $("#success-alert").hide(6000);
    $("#myWish").click(function showAlert() {
        $("#success-alert").alert();
        window.setTimeout(function() {
            $("#success-alert").alert('close');
        }, 2000);
    });

});
$('#userTable').DataTable();
</script>
@endsection

resources/views/quiz/quiz-category.blade.php
@extends('layouts.master')
@section('content')
@jquery
@toastr_js
@toastr_render
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quiz questions</h1>

                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">All Quiz</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                         
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="card-body table-responsive p-0">
                                    <table id="userTable" class="table table-striped table-bordered" cellspacing="0"
                                        width="100%">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Category Name</th>
                                                <th>Option 1</th>
                                                <th>Option 2</th>
                                                <th>Option 3</th>
                                                <th>Option 4</th>
                                                <th>Correct Option</th>
                                                <th>ACTION</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach($data as $quiz)
                                            <tr>
                                                <td>{{$quiz->id}}</td>
                                                <td>{{isset($quiz->categoryQuiz->subjects)?$quiz->categoryQuiz->subjects:'N/A'}}
                                                </td>
                                                <td>{{$quiz->opt1}}</td>
                                                <td>{{$quiz->opt2}}</td>
                                                <td>{{$quiz->opt3}}</td>
                                                <td>{{$quiz->opt4}}</td>
                                                <td>{{$quiz->correct}}</td>
                                                <td>
                                                    {{-- <a href="{{route('dashboard.quiz.create',['id'=>$quiz->id])}}" class="btn btn-danger"
                                                        onclick="return confirm('Are you sure ? to delete')"><i
                                                        class="fas fa-trash"></i>
                                                    </a> --}}
                                                    <a href="" class="btn btn-danger" data-id="{{$quiz->id}}">
                                                        <i class="fas fa-trash"></i>
                                                    </a> 
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    <!-- <a href="" class="btn btn-danger"
                                            onclick="return confirm('Are you sure ? to delete')"><i
                                            class="fas fa-trash"></i>
                                        </a> -->
                                </div>

                            </div>
                            <!-- /.d-flex -->
                        </div>
                    </div>
                    <!-- /.card -->


                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
</div>
<!-- /.content -->
<script>
$('#userTable').DataTable();
$(document).ready(function() {
    // $('#delteuser').click(function() {

    //        var deleteid = $(this).val();
    //     //    alert("deleteid");
    //        alert(deleteid);

    // });
});

// function ConfirmDelete(event) {
//     var x = confirm("Are you sure you want to delete?");
//     if (x) {
//         return true;
//     } else {
//         event.preventDefault();
//         return false;
//     }
// }
</script>

{{-- delete-quiz-question --}}
<script>
    $(document).ready(function(){
        $('.btn-danger').on('click', function(e) {
            e.preventDefault();
            var userId = $(this).data('id'); 
            swal({
                title: "Are you sure? to delete!",
                text: "Once deleted, you will not be able to recover this data!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'GET',
                        url: '{{ route('dashboard.quiz.del', ':id') }}'.replace(':id', userId),
                        data: {
                            _token: '{{ csrf_token() }}',
                        },
                        success: function(response) {
                            if (response.success) {
                                swal("Success!", "Successfully deleted!", "success")
                                .then(function() {
                                    flasher.success('Quiz delete successfully!');
                                    setTimeout(() => {
                                        location.reload();
                                    }, 2000);
                                });
                            } else {
                                swal("Error!", "An error occurred while deleting the quiz.", "error");
                            }
                        },
                        error: function() {
                            swal("Error!", "An error occurred while deleting the quiz.", "error");
                        }
                    });
                }
            });
        });
    });
</script>

@endsection